#ifndef SERCOM_PINOUT_H_INCLUDED
#define SERCOM_PINOUT_H_INCLUDED
#include <compiler.h>
/* SERCOM0 */
#define SERCOM0_PAD0_DEFAULT      PINMUX_PA08C_SERCOM0_PAD0
#define SERCOM0_PAD1_DEFAULT      PINMUX_PA09C_SERCOM0_PAD1
#define SERCOM0_PAD2_DEFAULT      PINMUX_PA10C_SERCOM0_PAD2
#define SERCOM0_PAD3_DEFAULT      PINMUX_PA11C_SERCOM0_PAD3

// SERCOM1 (SPI SERCOM)
#define SERCOM1_PAD0_DEFAULT      PINMUX_PA16C_SERCOM1_PAD0
#define SERCOM1_PAD1_DEFAULT      PINMUX_PA17C_SERCOM1_PAD1
#define SERCOM1_PAD2_DEFAULT      PINMUX_PA18C_SERCOM1_PAD2
#define SERCOM1_PAD3_DEFAULT      PINMUX_PA19C_SERCOM1_PAD3
// SERCOM2
#define SERCOM2_PAD0_DEFAULT      PINMUX_PA12C_SERCOM2_PAD0
#define SERCOM2_PAD1_DEFAULT      PINMUX_PA13C_SERCOM2_PAD1
#define SERCOM2_PAD2_DEFAULT      PINMUX_PA14C_SERCOM2_PAD2
#define SERCOM2_PAD3_DEFAULT      PINMUX_PA15C_SERCOM2_PAD3
// SERCOM3 (Radio USART)
#define SERCOM3_PAD0_DEFAULT      PINMUX_PA22C_SERCOM3_PAD0
#define SERCOM3_PAD1_DEFAULT      PINMUX_PA23C_SERCOM3_PAD1
#define SERCOM3_PAD2_DEFAULT      PINMUX_PA24C_SERCOM3_PAD2
#define SERCOM3_PAD3_DEFAULT      PINMUX_PA25C_SERCOM3_PAD3
// SERCOM4 (I2C SERCOM)
#define SERCOM4_PAD0_DEFAULT      PINMUX_PB12C_SERCOM4_PAD0
#define SERCOM4_PAD1_DEFAULT      PINMUX_PB13C_SERCOM4_PAD1
#define SERCOM4_PAD2_DEFAULT      PINMUX_PB14C_SERCOM4_PAD2
#define SERCOM4_PAD3_DEFAULT      PINMUX_PB15C_SERCOM4_PAD3
// SERCOM5
#define SERCOM5_PAD0_DEFAULT      PINMUX_PB16C_SERCOM5_PAD0
#define SERCOM5_PAD1_DEFAULT      PINMUX_PB17C_SERCOM5_PAD1
#define SERCOM5_PAD2_DEFAULT      PINMUX_PA20C_SERCOM5_PAD2
#define SERCOM5_PAD3_DEFAULT      PINMUX_PA21C_SERCOM5_PAD3

#endif /* SERCOM_PINOUT_H_INCLUDED */